### ISSUE TITLE
layout error in safari

### ISSUE THREAD

**Issue by cmdillon** [betaWeb/inputTags-jQuery-plugin#1]
hi! great plugin, but there seems to be a layout error in safari (mac, version 8.0.7 (10600.7.12))
the 'close-item' element is positioned bellow the tex baseline.

![screen shot 2015-08-01 at 10 50 25](https://cloud.githubusercontent.com/assets/1465141/9020384/27f2ed70-383b-11e5-82b7-0211245a2af2.png)

**Comment by betaWeb** [comment]
Hi! Thx, I'm gonna fix it as soon as possible !

**Comment by betaWeb** [comment]
Hi,

Sorry for the (long) wait.
The issue is fixed.
