### ISSUE TITLE
on blur contribution

### ISSUE THREAD

**Issue by ropic** [betaWeb/inputTags-jQuery-plugin#10]
use case: sometimes user only enter one value without hit enter then blur event could be used:

``` javascript
self._blur = function() {
          self.$input.on('blur', function() {
            if(self.$input.val().length > 0){
              e = $.Event('keyup');
              e.keyCode = 13;
              e.which = 13;
              self.$input.trigger(e);
            }
          });
        };
```

On initialization

``` javascript
self._blur();
```

**Comment by ropic** [comment]
maybe it's necessary to tell the users fire the event in case on submit button because blur is not fired

**Comment by betaWeb** [comment]
Hi @ropic,

Thx for the trick.
Maybe you could make a pull request :)
