### ISSUE TITLE
Enter keydown in cellphone not work chage of input

### ISSUE THREAD

**Issue by hortigado** [betaWeb/inputTags-jQuery-plugin#15]
When i want put a tag with enter the input change to the next

**Comment by trolllik** [comment]
Hi, on mobile only change method working. Сan't get it to work

**Comment by betaWeb** [comment]
@hortigado 
> the input change to the next

Explain please :) 
And what browser / OS ?

@trolllik can you explain your problem with example(s) please ? :)
