### ISSUE TITLE
How to refresh data in autocomplete?

### ISSUE THREAD

**Issue by ahmadkeren** [betaWeb/inputTags-jQuery-plugin#20]
Any way to refresh data in autocomplete?
Thanks

**Comment by ahmadkeren** [comment]
![Screen Shot 2022-07-13 at 10 11 14](https://user-images.githubusercontent.com/49072140/178642741-04c9f5c2-0a86-4494-a72f-2cb56bec48fc.png)
Solved, i add some custom method at js

**Comment by betaWeb** [comment]
Hi @ahmadkeren :)

what do you mean by "refresh data" ? Reset or change it completely ?
