### ISSUE TITLE
Specifying default values isn't working

### ISSUE THREAD

**Issue by corneschouten** [betaWeb/inputTags-jQuery-plugin#3]
Specifying default values like in the example you give on the documentation page isn't working.

`<input type="text" value="one,two,three" id="tags" />`
`$('#tags').inputTags();`

When you execute the code above you won't see any tags.

**Comment by betaWeb** [comment]
Thanks a lot for the review, I've fixed it ;)

**Comment by betaWeb** [comment]
Hello,

Sorry for the (long) wait.
I have no problem to specify default tags.
Have you wrap your code into a `jQuery(document).ready(function($) {});` ?
What is your browser ?
