### ISSUE TITLE
Autocomplete does not work

### ISSUE THREAD

**Issue by nvkhoa666** [betaWeb/inputTags-jQuery-plugin#7]
In your demo site (http://betaweb.github.io/inputTags-jQuery-plugin/), the autocomplete function does not work. Clicking on the input did show the list of tags, but clicking on one of those tags does nothing (it should add the tag to the input).

Please fix it, as I really like your plugin. Thank you!

**Comment by betaWeb** [comment]
Hello,

Sorry for the (long) wait. What is your browser ?

Thx :)

**Comment by nvkhoa666** [comment]
I'm using Chrome 52.0.2743.82 beta-m (64-bit), same to Firefox 49.0a2 (2016-07-21)

**Comment by betaWeb** [comment]
I fixed it :)
Tell me if everything works for you ?

**Comment by nvkhoa666** [comment]
Yes, it works now. Awesome!

**Comment by betaWeb** [comment]
Great ! :)

I close the issue.
