### ISSUE TITLE
contribution for mail validation

### ISSUE THREAD

**Issue by ropic** [betaWeb/inputTags-jQuery-plugin#9]
1. include error type email
2. include boolean option email
3. on validate function add the following case: 

`````` javascript
    case self.options.email:
    re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
              if(!re.test(value)){
                type = 'email';
              }
              break;````
``````

**Comment by betaWeb** [comment]
Hello,

Good idea, I add this right now :)

**Comment by ropic** [comment]
Hi, sorry it seems you forgot put the default email validation error message.

**Comment by betaWeb** [comment]
I fixed it ;)

Edit : If you activate emails validation, all tags must be of type email.

**Comment by ropic** [comment]
Ok, could be great having this on your documentation.

**Comment by betaWeb** [comment]
Yes, I have to take a few time to improve the documentation.
